### ISSUE TITLE
use 

### ISSUE THREAD

**Issue by imansedky5** [GSG-G9/WE-tools-week3#37]
https://github.com/GSG-G9/WE-tools-week3/blob/cc51eb08c4022d4ed92dc44a536cd9bf33a9db16/js/dom.js#L121-L124
you can use append() method instead of appendChild() and reduce the four lines into a single line!
[append method usage](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append)

**Comment by mAbadsa** [comment]
I am Replace This lines With one Lines by using append();
